example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import (
    create_wishlist_ajax,
    login_user,
    logout_user,
    register,
    show_wishlist,
    show_wishlist_xml,
    show_wishlist_json,
    show_wishlist_xml_by_id,
    show_wishlist_json_by_id,
    wishlist_ajax,
)

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('xml/', show_wishlist_xml, name='show_wishlist_xml'),
    path('json/', show_wishlist_json, name='show_wishlist_json'),
    path('xml/<int:id>/', show_wishlist_xml_by_id, name='show_wishlist_xml_by_id'),
    path('json/<int:id>/', show_wishlist_json_by_id, name='show_wishlist_json_by_id'),
    path('ajax', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit', create_wishlist_ajax, name='create_wishlist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishList(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms

from wishlist.models import BarangWishList


class CreateBarangWishlistForm(forms.ModelForm):
    class Meta:
        model = BarangWishList
        fields = ['nama_barang', 'harga_barang', 'deskripsi']

    nama_barang = forms.CharField(max_length=255)
    harga_barang = forms.IntegerField()
    deskripsi = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 6, 'style': 'resize: none;'})
    )

    def save(self, user_id, commit=True):
        item = super().save(commit=False)

        if commit:
            item.save()

        return item

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from wishlist.forms import CreateBarangWishlistForm
from wishlist.models import BarangWishList

import datetime
import json

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(
                reverse("wishlist:show_wishlist")
            )  # membuat response
            response.set_cookie(
                'last_login', str(datetime.datetime.now())
            )  # membuat cookie last_login dan menambahkannya ke dalam response

            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/wishlist/login')
def wishlist_ajax(request):
    form = CreateBarangWishlistForm()

    context = {'form': form}
    return render(request, 'wishlist_ajax.html', context)


@login_required(login_url='/wishlist/login')
def create_wishlist_ajax(request):
    if request.method == "POST":
        data = json.loads(request.body)

        BarangWishList.objects.create(
            nama_barang=data["nama_barang"],
            deskripsi=data["deskripsi"],
            harga_barang=data["harga_barang"],
        )

        return HttpResponse("Item created")

    return HttpResponseNotAllowed('Incorrect method')


@login_required(login_url='/wishlist/login')
def show_wishlist(request):
    data_barang_wishlist = BarangWishList.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Nayyara Airlangga Raharjo',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'wishlist.html', context)


def show_wishlist_xml(request):
    data = BarangWishList.objects.all()

    return HttpResponse(
        serializers.serialize('xml', data), content_type='application/xml'
    )


def show_wishlist_json(request):
    data = BarangWishList.objects.all()

    return HttpResponse(
        serializers.serialize('json', data), content_type='application/json'
    )


def show_wishlist_xml_by_id(request, id):
    data = BarangWishList.objects.filter(pk=id)

    return HttpResponse(
        serializers.serialize('xml', data), content_type='application/xml'
    )


def show_wishlist_json_by_id(request, id):
    data = BarangWishList.objects.filter(pk=id)

    return HttpResponse(
        serializers.serialize('json', data), content_type='application/json'
    )

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="login">

  <h1>Login</h1>

  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Username: </td>
        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
      </tr>

      <tr>
        <td>Password: </td>
        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn login_btn" type="submit" value="Login"></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<div class="login">

  <h1>Formulir Registrasi</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Daftar" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

</div>

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">{{ nama }}</a>
    <div class="d-flex" role="search">
      <button class="btn btn-outline-success">
        <a href="{% url 'wishlist:logout' %}">
          Logout
        </a>
      </button>
    </div>
  </div>
</nav>

<table>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{ barang.nama_barang }}</th>
            <th>{{ barang.harga_barang }}</th>
            <th>{{ barang.deskripsi }}</th>
        </tr>
    {% endfor %}
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">{{ nama }}</a>
    <div class="d-flex" role="search">
      <button class="btn btn-outline-success">
        <a href="{% url 'wishlist:logout' %}">
          Logout
        </a>
      </button>
    </div>
  </div>
</nav>

<table id="wishlist_table"> 
  {% comment %} Tambahkan data di bawah baris ini {% endcomment %} 
</table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button type="button" onclick="fetchWishlist();">Refresh</button>

<form method="POST" id="wishlist-form">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td><input class="btn login_btn" type="submit" value="Create"></td>
    </tr>
  </table>
</form>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}